version: "3" # optional since v1.27.0


services:
  app:    
    container_name: service_nestjs
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "3010:3010"
      # - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/node/app
    depends_on:
      - postgresql      
    extra_hosts:
      - "host.docker.internal:172.17.0.1" 
     

  postgresql:
    container_name: db_postgres
    build: .docker/postgres
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    environment:      
      POSTGRES_DB: "db_banking"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
      # - ${DB_PORT}:5432 
    extra_hosts:
      - "host.docker.internal:172.17.0.1" 

  pgadmin:
    image: dpage/pgadmin4:6.21
    tty: true
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@user.com"
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "9000:80"
    depends_on:
      - postgresql
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    

