version: '3' # optional since v1.27.0


services:
  app:    
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      # - '3000:3000'
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/node/app
    depends_on:
      - database
     

  database:
    build: .docker/postgres
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      # - '5432:5432'
      - ${DB_PORT}:5432

  pgadmin:
    image: dpage/pgadmin4:latest    
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456  
    ports:
      - 9000:80

